version: '3.8'
services:
  database:
    image: mysql:latest
    volumes:
      - ./mysql/db:/var/lib/mysql
    restart: always
    ports:
      - 7769:3306
    environment:
      MYSQL_DATABASE: nest-api
      MYSQL_USER: mithosk
      MYSQL_PASSWORD: mithosk